# SPDX-License-Identifier: GPL-2.0-or-later
# Makefile for the video capture/playback device drivers.
# Copyright 2010 Steven King <sfking@fdwdc.com>
#Copyright(c) 2022-2027 Allwinnertech Co., Ltd
# Each configuration option enables a list of files.
obj-$(CONFIG_CSI_VIN)           += actuator.o

obj-$(CONFIG_ACTUATOR)   += ad5820_act.o
obj-$(CONFIG_ACTUATOR)   += dw9714_act.o
obj-$(CONFIG_ACTUATOR)   += ov8825_act.o
obj-$(CONFIG_ACTUATOR)   += an41908a_act.o

